import type { Metadata } from "next";
import { Heebo, Inter } from "next/font/google"
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const heebo = Heebo({subsets:["latin"],weight:["400","700","900","500"]});
const inter = Inter({subsets:["latin"],weight:["400","700","500"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={heebo.className}>
        <Header font={inter}/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
